import './globals.css'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'

//components
import Navbar from './components/navbar'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Fred's Site!",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
    <body className={raleway.className}>
      <Navbar />
      {children}
    </body>
    </html>
  )
}
